import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/shared/navBar/NavBar";
import { Footer } from "@/components/shared/Footer";
import WhatsAppButton from "@/components/shared/whatsAppButton/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed inset-0 -z-10">
          {/* Gradiente base - este está bien */}
          <div className="absolute inset-0 bg-linear-to-br from-black via-gray-950 to-black"></div>

          {/* Efectos optimizados usando CSS puro en lugar de blur-3xl */}
          <div
            className="absolute inset-0"
            style={{
              background: `
            radial-gradient(circle at 25% 25%, rgba(220, 38, 38, 0.03) 0%, transparent 50%),
            radial-gradient(circle at 75% 67%, rgba(249, 115, 22, 0.03) 0%, transparent 50%)
          `,
            }}
          ></div>
        </div>
        <NavBar />
        <main className="m-auto">{children}</main>

        <Footer />

        <WhatsAppButton />

        {/* <!-- Toaster para notificaciones solo en páginas públicas --> */}
        {/* {!isDashboard && <ToasterProvider client:load />} */}
        {/* <!-- <ToasterProvider client:load /> --> */}
      </body>
    </html>
  );
}
